// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGateway) DeepCopyInto(out *IBMApplicationGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGateway.
func (in *IBMApplicationGateway) DeepCopy() *IBMApplicationGateway {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMApplicationGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayAznHeader) DeepCopyInto(out *IBMApplicationGatewayAznHeader) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayAznHeader.
func (in *IBMApplicationGatewayAznHeader) DeepCopy() *IBMApplicationGatewayAznHeader {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayAznHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayConfiguration) DeepCopyInto(out *IBMApplicationGatewayConfiguration) {
	*out = *in
	out.AznHeader = in.AznHeader
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayConfiguration.
func (in *IBMApplicationGatewayConfiguration) DeepCopy() *IBMApplicationGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayDeployment) DeepCopyInto(out *IBMApplicationGatewayDeployment) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayDeployment.
func (in *IBMApplicationGatewayDeployment) DeepCopy() *IBMApplicationGatewayDeployment {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayList) DeepCopyInto(out *IBMApplicationGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBMApplicationGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayList.
func (in *IBMApplicationGatewayList) DeepCopy() *IBMApplicationGatewayList {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMApplicationGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewaySpec) DeepCopyInto(out *IBMApplicationGatewaySpec) {
	*out = *in
	out.Deployment = in.Deployment
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]IBMApplicationGatewayConfiguration, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewaySpec.
func (in *IBMApplicationGatewaySpec) DeepCopy() *IBMApplicationGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayStatus) DeepCopyInto(out *IBMApplicationGatewayStatus) {
	*out = *in
	if in.PodNames != nil {
		in, out := &in.PodNames, &out.PodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayStatus.
func (in *IBMApplicationGatewayStatus) DeepCopy() *IBMApplicationGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayStatus)
	in.DeepCopyInto(out)
	return out
}
