# Copyright contributors to the IBM Application Gateway Operator project

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: image-registry.openshift-image-registry.svc:5000/openshift/ibm-application-gateway-operator
  newTag: 24.3.0
