//go:build !ignore_autogenerated

/*
 * Copyright contributors to the IBM Application Gateway Operator project
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomAnnotation) DeepCopyInto(out *CustomAnnotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomAnnotation.
func (in *CustomAnnotation) DeepCopy() *CustomAnnotation {
	if in == nil {
		return nil
	}
	out := new(CustomAnnotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGateway) DeepCopyInto(out *IBMApplicationGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGateway.
func (in *IBMApplicationGateway) DeepCopy() *IBMApplicationGateway {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMApplicationGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayConfiguration) DeepCopyInto(out *IBMApplicationGatewayConfiguration) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]IBMApplicationGatewayHeaders, len(*in))
		copy(*out, *in)
	}
	if in.PostData != nil {
		in, out := &in.PostData, &out.PostData
		*out = make([]IBMApplicationGatewayPostData, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayConfiguration.
func (in *IBMApplicationGatewayConfiguration) DeepCopy() *IBMApplicationGatewayConfiguration {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayDeployment) DeepCopyInto(out *IBMApplicationGatewayDeployment) {
	*out = *in
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	out.ReadinessProbe = in.ReadinessProbe
	out.LivenessProbe = in.LivenessProbe
	if in.CustomAnnotations != nil {
		in, out := &in.CustomAnnotations, &out.CustomAnnotations
		*out = make([]CustomAnnotation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayDeployment.
func (in *IBMApplicationGatewayDeployment) DeepCopy() *IBMApplicationGatewayDeployment {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayHeaders) DeepCopyInto(out *IBMApplicationGatewayHeaders) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayHeaders.
func (in *IBMApplicationGatewayHeaders) DeepCopy() *IBMApplicationGatewayHeaders {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayHeaders)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayList) DeepCopyInto(out *IBMApplicationGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IBMApplicationGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayList.
func (in *IBMApplicationGatewayList) DeepCopy() *IBMApplicationGatewayList {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IBMApplicationGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayPostData) DeepCopyInto(out *IBMApplicationGatewayPostData) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayPostData.
func (in *IBMApplicationGatewayPostData) DeepCopy() *IBMApplicationGatewayPostData {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayPostData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayProbe) DeepCopyInto(out *IBMApplicationGatewayProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayProbe.
func (in *IBMApplicationGatewayProbe) DeepCopy() *IBMApplicationGatewayProbe {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewaySpec) DeepCopyInto(out *IBMApplicationGatewaySpec) {
	*out = *in
	in.Deployment.DeepCopyInto(&out.Deployment)
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = make([]IBMApplicationGatewayConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewaySpec.
func (in *IBMApplicationGatewaySpec) DeepCopy() *IBMApplicationGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IBMApplicationGatewayStatus) DeepCopyInto(out *IBMApplicationGatewayStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IBMApplicationGatewayStatus.
func (in *IBMApplicationGatewayStatus) DeepCopy() *IBMApplicationGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(IBMApplicationGatewayStatus)
	in.DeepCopyInto(out)
	return out
}
