---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmapplicationgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmapplicationgateways/finalizers
  verbs:
  - update
- apiGroups:
  - ibm.com
  resources:
  - ibmapplicationgateways/status
  verbs:
  - get
  - patch
  - update
