apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-application-gateway-operator
  labels:
    app: ibm-application-gateway-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-application-gateway-operator
      app: ibm-application-gateway-injector
  template:
    metadata:
      labels:
        name: ibm-application-gateway-operator
        app: ibm-application-gateway-injector
    spec:
      serviceAccountName: ibm-application-gateway-operator
      containers:
        - name: ibm-application-gateway-operator
          image: ibmcom/ibm-application-gateway-operator:latest
          command:
          - ibm-application-gateway-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-application-gateway-operator"
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: ibm-application-gateway-injector-webhook-certs
