apiVersion: v1
kind: Service
metadata:
  name: ibm-application-gateway-injector-webhook-svc
  namespace: default
  labels:
    app: ibm-application-gateway-injector
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: ibm-application-gateway-injector