# Copyright contributors to the IBM Application Gateway Operator project

# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/ibm.com_ibmapplicationgateways.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
- patches/webhook_in_ibmapplicationgateways.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

- patches/cainjection_in_ibmapplicationgateways.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
